config/routes.rb
Rails.application.routes.draw do

  root 'facilities#index'

  post '/rate' => 'rater#create', :as => 'rate'

  get "/auth/twitter/callback" => "sessions#create"
  get 'auth/failure', to: redirect('/')

  get "/signout" => "sessions#destroy", :as => :signout
  

  resources :reviews

  resources :users

  resources :doctors

  resources :facilities


end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :doctors, :through => :facility_doctor
	has_many :facility_doctors
	letsrate_rateable "quality"
	acts_as_mappable :default_units => :kms,
					:lng_column_name => :longitude,
					:lat_column_name => :latitude
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @facility = Facility.find(params[:id])
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :category, :town, :district, :region, :latitude, :longitude, :phone, :website, :specialty)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :town %><br>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br>
    <%= f.text_area :specialty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<div id='map' class="well"></div>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h2><%= @facility.name %></h2>
    <p><%= @facility.town %>, <%= @facility.district %> District, <%= @facility.region %> Region</p>
    <div id="phoneWebsite"></div>
  </div>

  <div class="col-md-3 col-md-offset-3" style="margin-top: 25px;">
    <h5 id="stars"> <%= rating_for @facility, "quality" %> </h5>
    <p><%= @facility.category %></p>
  </div>
</div>

<div class="row">
  <div id="show_map" class="well col-md-12"></div>
</div>

<p id="facility_id" style="display: none;"><%= @facility.id %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Reviews</h3>
    <table class="table">
      <tr>
        <th>Rating</th>
        <th>Comments</th>
        <th>Rater</th>
      </tr>
      <tr>
        <td>4 Stars</td>
        <td>This clinic is better than most.  The doctor was nice and on time.</td>
        <td>Kofi C.</td>
      </tr>
    </table>
  </div>
</div>

<footer class="col-md-12 text-center">
<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>
</footer>